

./WWW_STEP011_analyis_v2_SMS_ENSO_CRU_klizno.sh
./WWW_STEP011_analyis_v2_SMS_NAO_CRU_klizno.sh
./WWW_STEP011_analyis_v2_SMS_ENSO_ERA40_klizno.sh
./WWW_STEP011_analyis_v2_SMS_NAO_ERA40_klizno.sh
./WWW_STEP011_analyis_v2_SMS_ENSO_model_per_model_klizno.sh
./WWW_STEP011_analyis_v2_SMS_NAO_model_per_model_klizno.sh

